
algorithm: bole_seq_proxy.BoleFID

algorithm_parameters:
  # Model
  n_layers: 2
  n_heads: 2
  k_interests: 3
  time_span: 1200
  c: 0.5
  time_bins: 0,1,8,20,40,120,620
  hidden_size: 8
  inner_size: 10
  hidden_dropout_prob: 0.2
  attn_dropout_prob: 0.2
  hidden_act: 'gelu'
  layer_norm_eps: 0.00005
  max_seq_length: 5
  initializer_range: 0.02
  loss_type: 'BPR'

  # training settings
  epochs: 2
  train_batch_size: 20
  learner: adam
  learning_rate: 0.001
  eval_step: 1                               #
  stopping_step: 4                          #
  clip_grad_norm: ~
  weight_decay: 0.0
  reg_weight: 0.01

  valid_metric: Hit@10
  valid_metric_bigger: True
  metrics: ["Hit"]
  topk: [10]

  neg_sampling:
    dict:
      uniform: 10